name: CI/CD for Expo Project with Bun

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          bun --version  # Ensure Bun is installed

      # Step 4: Use Bun to install dependencies
      - name: Install dependencies with Bun
        run: |
          echo "Verifying Bun installation..."
          which bun || (echo "Bun not found" && exit 1)
          bun install

      # Step 5: Run Prettier check
      - name: Run Prettier
        run: bun run prettier:check

      # Step 6: Run ESLint check
      - name: Run ESLint
        run: bun run lint

      # Step 7: Run TypeScript check
      # - name: Run TypeScript
      #   run: bun run type-check

      # Step 8: Run Tests
      - name: Run Tests
        run: bun test
